[package]
name = "askme-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "7.0.0"
sha256 = "1.0.3"
sqlite3 = "0.24.0"
